// <auto-generated />
namespace LouManChoose.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedanothercontroller : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedanothercontroller));
        
        string IMigrationMetadata.Id
        {
            get { return "201706141938044_added another controller"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
